### ISSUE TITLE
Error: Cannot find module 'webpack-cli/bin/config-yargs'

### ISSUE THREAD

**Issue by xihaoxiaohao** [Louis-7/angular-monaco-languageclient#2]
I follow the instruction, but when I run` npm start`, it failed with this error.

```
> webpack-dev-server --port=4200

The CLI moved into a separate package: webpack-cli
Please install 'webpack-cli' in addition to webpack itself to use the CLI
-> When using npm: npm i -D webpack-cli
-> When using yarn: yarn add -D webpack-cli
internal/modules/cjs/loader.js:605
    throw err;
    ^

Error: Cannot find module 'webpack-cli/bin/config-yargs'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)

```

**Comment by Louis-7** [comment]
Seems the error related to different webpack version? So have you tried to install "webpack-cli" separately?

**Comment by xihaoxiaohao** [comment]
I tried reinstall webpack-cli, and change webpack-dev-server to 2.11.0, but giving me the below error while I run npm start:

```
> angular-monaco@0.0.0 start /Users/user/Documents/ps/angular-monaco-languageclient
> webpack-dev-server --port=4200

 10% building modules 3/3 modules 0 activeProject is running at http://localhost:4200/
webpack output is served from /
404s will fallback to /index.html
Hash: 0d542be75101848fdca3                                                              
Version: webpack 3.11.0
Time: 3890ms
 10 assets
   [0] multi (webpack)-dev-server/client?http://localhost:4200 ./src/main.ts 40 bytes {main} [built]
   [1] multi (webpack)-dev-server/client?http://localhost:4200 ./src/polyfills.ts 40 bytes {polyfills} [built]
   [2] multi (webpack)-dev-server/client?http://localhost:4200 ./src/styles.scss 40 bytes {styles} [built]
[./node_modules/@angular/core/esm2015/core.js] ./node_modules/@angular/core/esm2015/core.js 547 kB {vendor} [built]
[./node_modules/@angular/platform-browser-dynamic/esm2015/platform-browser-dynamic.js] ./node_modules/@angular/platform-browser-dynamic/esm2015/platform-browser-dynamic.js 22.2 kB {vendor} [built]
[./node_modules/core-js/es7/reflect.js] ./node_modules/core-js/es7/reflect.js 510 bytes {polyfills} [built]
[./node_modules/loglevel/lib/loglevel.js] ./node_modules/loglevel/lib/loglevel.js 7.86 kB {inline} [built]
[./node_modules/strip-ansi/index.js] ./node_modules/strip-ansi/index.js 161 bytes {inline} [built]
[./node_modules/url/url.js] ./node_modules/url/url.js 23.3 kB {inline} [built]
[./node_modules/webpack-dev-server/client/index.js?http://localhost:4200] (webpack)-dev-server/client?http://localhost:4200 7.93 kB {inline} [built]
[./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.67 kB {inline} [built]
[./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.08 kB {inline} [built]
[./node_modules/webpack/hot ^\.\/log$] (webpack)/hot nonrecursive ^\.\/log$ 170 bytes {inline} [built]
[./src\main.ts] ./src/main.ts 371 bytes {main} [built]
[./src\polyfills.ts] ./src/polyfills.ts 3.09 kB {polyfills} [built]
    + 141 hidden modules

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './app/app.module' in '/Users/user/Documents/ps/angular-monaco-languageclient/src\'
 @ ./src/main.ts 3:0-45
 @ multi (webpack)-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './environments/environment' in '/Users/user/Documents/ps/angular-monaco-languageclient/src\'
 @ ./src/main.ts 4:0-57
 @ multi (webpack)-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in multi (webpack)-dev-server/client?http://localhost:4200 ./src/styles.scss
Module not found: Error: Can't resolve './src\styles.scss' in '/Users/user/Documents/ps/angular-monaco-languageclient'
 @ multi (webpack)-dev-server/client?http://localhost:4200 ./src/styles.scss

ERROR in   Error: Child compilation failed:
  Entry module not found: Error: Can't resolve '/Users/user/Documents/ps/angular-monaco-languageclient/src\index.html' in '/Users/user/Documents/ps/angular  -monaco-languageclient':
  Error: Can't resolve '/Users/user/Documents/ps/angular-monaco-languageclient/src\index.html' in '/Users/user/Documents/ps/angular-monaco-languageclient'
  
  - compiler.js:76 
    [angular-monaco-languageclient]/[html-webpack-plugin]/lib/compiler.js:76:16
  
  - Compiler.js:300 compile
    [angular-monaco-languageclient]/[webpack]/lib/Compiler.js:300:11
  
  - Compiler.js:510 applyPluginsAsync.err
    [angular-monaco-languageclient]/[webpack]/lib/Compiler.js:510:14
  
  - Tapable.js:202 next
    [angular-monaco-languageclient]/[tapable]/lib/Tapable.js:202:11
  
  - CachePlugin.js:78 Compiler.<anonymous>
    [angular-monaco-languageclient]/[webpack]/lib/CachePlugin.js:78:5
  
  - Tapable.js:206 Compiler.applyPluginsAsyncSeries
    [angular-monaco-languageclient]/[tapable]/lib/Tapable.js:206:13
  
  - Compiler.js:507 compilation.seal.err
    [angular-monaco-languageclient]/[webpack]/lib/Compiler.js:507:11
  
  - Tapable.js:195 Compilation.applyPluginsAsyncSeries
    [angular-monaco-languageclient]/[tapable]/lib/Tapable.js:195:46
  
  - Compilation.js:677 applyPluginsAsync.err
    [angular-monaco-languageclient]/[webpack]/lib/Compilation.js:677:19
  
  - Tapable.js:195 Compilation.applyPluginsAsyncSeries
    [angular-monaco-languageclient]/[tapable]/lib/Tapable.js:195:46
  
  - Compilation.js:668 applyPluginsAsync.err
    [angular-monaco-languageclient]/[webpack]/lib/Compilation.js:668:11
  
  - Tapable.js:195 Compilation.applyPluginsAsyncSeries
    [angular-monaco-languageclient]/[tapable]/lib/Tapable.js:195:46
  
  - Compilation.js:663 applyPluginsAsync.err
    [angular-monaco-languageclient]/[webpack]/lib/Compilation.js:663:10
  
  - Tapable.js:195 Compilation.applyPluginsAsyncSeries
    [angular-monaco-languageclient]/[tapable]/lib/Tapable.js:195:46
  
  - Compilation.js:659 applyPluginsAsyncSeries
    [angular-monaco-languageclient]/[webpack]/lib/Compilation.js:659:9
  
  - Tapable.js:195 Compilation.applyPluginsAsyncSeries
    [angular-monaco-languageclient]/[tapable]/lib/Tapable.js:195:46
  

Child html-webpack-plugin for "index.html":
    
    ERROR in Entry module not found: Error: Can't resolve '/Users/user/Documents/ps/angular-monaco-languageclient/src\index.html' in '/Users/user/Documents/ps/angular-monaco-languageclient'
webpack: Failed to compile.

```

**Comment by Louis-7** [comment]
```
Module not found: Error: Can't resolve './app/app.module' in '/Users/user/Documents/ps/angular-monaco-languageclient/src\'
 @ ./src/main.ts 3:0-45
```
There is a "\" at the end of the URL, I review my webpack config and I found that I use many "\\" in it. I guess webpack loader can't resolve the correct path. You could try to use "/" instead of "\\".

I will review the build process again and fix the URL problem. BTW, if you think it's related to webpack version, you can fix the version number in package.json and have a try.

**Comment by Louis-7** [comment]
@xihaoxiaohao I update the dependencies and it's working for me now. You can remove your node_modules and re-install.

**Comment by xihaoxiaohao** [comment]
Hi @Louis-7 thanks for the update. I removed the old folder and re clone the repository, install the packages and run `npm start`, I faced the same url error as above described. Then, I changed the webpack config as below:

```
--- a/webpack.config.js
+++ b/webpack.config.js
@@ -146,13 +146,13 @@ module.exports = {
   },
   "entry": {
     "main": [
-      "./src\\main.ts"
+      "./src/main.ts"
     ],
     "polyfills": [
-      "./src\\polyfills.ts"
+      "./src/polyfills.ts"
     ],
     "styles": [
-      "./src\\styles.scss"
+      "./src/styles.scss"
     ]
   },
   "output": {
@@ -431,7 +431,7 @@ module.exports = {
     }),
     new NamedLazyChunksWebpackPlugin(),
     new HtmlWebpackPlugin({
-      "template": "./src\\index.html",
+      "template": "./src/index.html",
       "filename": "./index.html",
       "hash": false,
       "inject": true,

```

Then I run the `npm start` again, it gives me the below error:

```
> webpack-dev-server --port=4200

 10% building modules 3/3 modules 0 activeProject is running at http://localhost:4200/
webpack output is served from /
404s will fallback to /index.html
Hash: f2d85e0ff2f8669ae306                                                           
Version: webpack 3.12.0
Time: 3151ms
 8 assets
   [0] multi (webpack)-dev-server/client?http://localhost:4200 ./src/main.ts 40 bytes {main} [built]
   [1] multi (webpack)-dev-server/client?http://localhost:4200 ./src/polyfills.ts 40 bytes {polyfills} [built]
   [2] multi (webpack)-dev-server/client?http://localhost:4200 ./src/styles.scss 40 bytes {styles} [built]
[./node_modules/ansi-html/index.js] ./node_modules/ansi-html/index.js 4.26 kB {inline} [built]
[./node_modules/loglevel/lib/loglevel.js] ./node_modules/loglevel/lib/loglevel.js 7.86 kB {inline} [built]
[./node_modules/strip-ansi/index.js] ./node_modules/strip-ansi/index.js 161 bytes {inline} [built]
[./node_modules/url/url.js] ./node_modules/url/url.js 23.3 kB {inline} [built]
[./node_modules/webpack-dev-server/client/index.js?http://localhost:4200] (webpack)-dev-server/client?http://localhost:4200 7.93 kB {inline} [built]
[./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.67 kB {inline} [built]
[./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.08 kB {inline} [built]
[./node_modules/webpack/hot ^\.\/log$] (webpack)/hot nonrecursive ^\.\/log$ 170 bytes {inline} [built]
[./node_modules/webpack/hot/emitter.js] (webpack)/hot/emitter.js 77 bytes {inline} [built]
[./src/main.ts] ./src/main.ts 0 bytes {main} [built]
[./src/polyfills.ts] ./src/polyfills.ts 0 bytes {polyfills} [built]
[./src/styles.scss] ./src/styles.scss 100 bytes {styles} [built]
    + 15 hidden modules

ERROR in node_modules/monaco-editor-core/monaco.d.ts(8,14): error TS2300: Duplicate identifier 'Thenable'.
node_modules/monaco-editor-core/monaco.d.ts(21,15): error TS2300: Duplicate identifier 'Emitter'.
node_modules/monaco-editor-core/monaco.d.ts(29,3): error TS2300: Duplicate identifier 'Ignore'.
node_modules/monaco-editor-core/monaco.d.ts(30,3): error TS2300: Duplicate identifier 'Info'.
node_modules/monaco-editor-core/monaco.d.ts(31,3): error TS2300: Duplicate identifier 'Warning'.
node_modules/monaco-editor-core/monaco.d.ts(32,3): error TS2300: Duplicate identifier 'Error'.
node_modules/monaco-editor-core/monaco.d.ts(36,3): error TS2300: Duplicate identifier 'Hint'.
node_modules/monaco-editor-core/monaco.d.ts(37,3): error TS2300: Duplicate identifier 'Info'.
node_modules/monaco-editor-core/monaco.d.ts(38,3): error TS2300: Duplicate identifier 'Warning'.
node_modules/monaco-editor-core/monaco.d.ts(39,3): error TS2300: Duplicate identifier 'Error'.
node_modules/monaco-editor-core/monaco.d.ts(45,14): error TS2300: Duplicate identifier 'TValueCallback'.
node_modules/monaco-editor-core/monaco.d.ts(47,14): error TS2300: Duplicate identifier 'ProgressCallback'.
node_modules/monaco-editor-core/monaco.d.ts(50,15): error TS2300: Duplicate identifier 'Promise'.
node_modules/monaco-editor-core/monaco.d.ts(91,15): error TS2300: Duplicate identifier 'CancellationTokenSource'.
node_modules/monaco-editor-core/monaco.d.ts(121,15): error TS2300: Duplicate identifier 'Uri'.
node_modules/monaco-editor-core/monaco.d.ts(194,3): error TS2300: Duplicate identifier 'Unknown'.
node_modules/monaco-editor-core/monaco.d.ts(195,3): error TS2300: Duplicate identifier 'Backspace'.
node_modules/monaco-editor-core/monaco.d.ts(196,3): error TS2300: Duplicate identifier 'Tab'.
node_modules/monaco-editor-core/monaco.d.ts(197,3): error TS2300: Duplicate identifier 'Enter'.
node_modules/monaco-editor-core/monaco.d.ts(198,3): error TS2300: Duplicate identifier 'Shift'.
node_modules/monaco-editor-core/monaco.d.ts(199,3): error TS2300: Duplicate identifier 'Ctrl'.
node_modules/monaco-editor-core/monaco.d.ts(200,3): error TS2300: Duplicate identifier 'Alt'.
node_modules/monaco-editor-core/monaco.d.ts(201,3): error TS2300: Duplicate identifier 'PauseBreak'.
node_modules/monaco-editor-core/monaco.d.ts(202,3): error TS2300: Duplicate identifier 'CapsLock'.
node_modules/monaco-editor-core/monaco.d.ts(203,3): error TS2300: Duplicate identifier 'Escape'.
node_modules/monaco-editor-core/monaco.d.ts(204,3): error TS2300: Duplicate identifier 'Space'.
node_modules/monaco-editor-core/monaco.d.ts(205,3): error TS2300: Duplicate identifier 'PageUp'.
```

**Comment by Louis-7** [comment]
OH...I forgot to fix the webpack config.

For the  Typescript compilation error -> https://github.com/Louis-7/angular-monaco-languageclient/blob/master/README.md, read "Prepare".
The libraries I use have conflicts of the identifier. You can expect ngx-monaco-editor or monaco-languageclient to fix that in furture.

**Comment by Louis-7** [comment]
fix the webpack config issue just now.

**Comment by xihaoxiaohao** [comment]
Thank you so much @Louis-7 got it work!

Is there any plan to migrate it to [react-monaco-editor](https://github.com/react-monaco-editor/react-monaco-editor)? I spent a lot of time and couldn't find any example online using React with the Monaco language server. Would be really appreciate it if you can give an example 😀

**Comment by Louis-7** [comment]
Currently no plan, I think it's very similar to my demo. monaco-languageclient perfectly show you how to connect to the language sever: https://github.com/TypeFox/monaco-languageclient/blob/master/example/src/client.ts. You can give a try.
